
HOST = "0.0.0.0"
PORT = 8080
STATIC_DIRECTORY = "frontend_system/static"
TEMPLATE_DIRECTORY = "frontend_system/templates"
AUTO_REFRESH_INTERVAL_MS = 5000
LONG_POLL_TIMEOUT_SECONDS = 30
MAX_TIMELINE_EVENTS = 1000
MAX_NOTIFICATIONS = 500
ENABLE_CORS = True
CORS_ORIGINS = ["*"]
AUTH_ENABLED = False
AUTH_TOKEN = "uci-admin-token"
LOG_LEVEL = "INFO"
LOG_FILE = "logs/frontend.log"
THEME = "dark"
PAGE_SIZE_DEFAULT = 50
PAGE_SIZE_MAX = 200
