from . import python_function_template
from . import python_class_template
from . import pipeline_template
from . import api_endpoint_template
from . import data_processor_template
from . import cli_tool_template
from . import test_template
from . import config_template
from . import dockerfile_template
from . import makefile_template
from . import shell_script_template
from . import capability_plugin_template
from . import strategy_plugin_template